### ISSUE TITLE
Add Groupdate setup for mysql to README

### ISSUE THREAD

**Issue by peterkos** [codeRIT/hackathon-manager#253]
Pretty much just this line should be added:
```
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
```

Error is below for reference.

```
ERROR["test_: while authenticated as an admin should allow access to all data endpoints. ", #<Minitest::Reporters::Suite:0x00007f86f7160348 @name="Manage::DashboardControllerTest">, 8.280117999998765]
 test_: while authenticated as an admin should allow access to all data endpoints. #Manage::DashboardControllerTest (8.28s)
Minitest::UnexpectedError:         Groupdate::Error: Database missing time zone support for Etc/UTC - see https://github.com/ankane/groupdate#for-mysql
            app/controllers/manage/dashboard_controller.rb:135:in `block in activity_chart_data'
            app/controllers/manage/dashboard_controller.rb:115:in `each'
            app/controllers/manage/dashboard_controller.rb:115:in `activity_chart_data'
            app/controllers/manage/dashboard_controller.rb:20:in `todays_activity_data'
            test/controllers/manage/dashboard_controller_test.rb:66:in `block (3 levels) in <class:DashboardControllerTest>'
            test/controllers/manage/dashboard_controller_test.rb:65:in `each'
            test/controllers/manage/dashboard_controller_test.rb:65:in `block (2 levels) in <class:DashboardControllerTest>'
            test/controllers/manage/dashboard_controller_test.rb:51:in `instance_exec'
            test/controllers/manage/dashboard_controller_test.rb:51:in `block in create_test_from_should_hash'

```

**Comment by cbaudouinjr** [comment]
I'm no longer able to replicate this issue on my end. @peterkos is this still an issue?
